version: 2
jobs:
    build:
      docker:
        - image: clearhaus/dotnet
      steps:
        - checkout
        - run:
            name: Execute Gateway tests
            command: |
              IFS= export RSAKEY=$(echo $RSAKEYBASE64 | base64 --decode)
              cd Gateway.Test
              dotnet restore
              dotnet test
        - run:
            name: Execute MPI tests
            command: |
              cd MPI.Test
              dotnet restore
              dotnet test

workflows:
  version: 2
  test:
    jobs:
      - build
