version: 2
jobs:
    build:
      docker:
        - image: clearhaus/dotnet
      steps:
        - checkout
        - run:
            name: Execute Gateway tests
            command: |
              IFS= export RSAKEY=$(echo $RSAKEYBASE64 | base64 --decode)
              cd Gateway.Test
              dotnet restore
              dotnet test
        - run:
            name: Execute MPI tests
            command: |
              cd MPI.Test
              dotnet restore
              dotnet test

workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  test:
    jobs:
      - build
