version: 2
jobs:
    build:
      docker:
        - image: microsoft/dotnet:latest
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              apt-get update
              apt-get install -y \
              mono-runtime \
              libmono-system-core4.0-cil \
              libmono-system-xml-linq4.0-cil
        - run:
            command: |
              cd Gateway.Test
              dotnet restore
              dotnet test
        - run:
            command: |
              cd MPI.Test
              dotnet restore
              dotnet test

workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  test:
    jobs:
      - build
